### ISSUE TITLE
Scegliere quali pagine lasciare al momento

### ISSUE THREAD

**Issue by aborruso** [opendatacampania/nonportaleregionecampania#2]
@marcoalfano fatemi sapere se ci sono pagine da rimuovere

**Comment by marcoalfano** [comment]
Leverei pagina 'linked open data' (al limite la reintroduciamo dopo aver fatto le modifiche opportune).
Il resto lo lascerei, si tratta solo di customizzarlo per la Campania

**Comment by marcoalfano** [comment]
Non vedo pìù la pagina 'proponi'. Quella deve rimanere.

**Comment by aborruso** [comment]
@marcoalfano l'avevo rimossa, perché dovevo creare nuovo form.

Fatto
