### ISSUE TITLE
Modificare il testo con i riferimenti alla Campania

### ISSUE THREAD

**Issue by aborruso** [opendatacampania/nonportaleregionecampania#3]

**Comment by marcoalfano** [comment]
@aborruso Se mi dici dove sono i testi posso provare a modificarli io

**Comment by aborruso** [comment]
@marcoalfano i due file principali sono:
- [https://github.com/opendatacampania/nonportaleregionecampania/blob/gh-pages/index.html](https://github.com/opendatacampania/nonportaleregionecampania/blob/gh-pages/index.html)
- [https://github.com/opendatacampania/nonportaleregionecampania/blob/gh-pages/cosa.html](https://github.com/opendatacampania/nonportaleregionecampania/blob/gh-pages/cosa.html)

In edit puoi andare da qui: 

![2016-02-25_16h18_38](https://cloud.githubusercontent.com/assets/30607/13323815/8186ace8-dbdb-11e5-81e6-04a913e7bf91.png)
