### ISSUE TITLE
url non-portale campano

### ISSUE THREAD

**Issue by marcoalfano** [opendatacampania/nonportaleregionecampania#4]
@aborruso si può collegare il nonportale campano a opendatacampania.it e fare diventare l'url nonportale.opendatacampania.it come quello siciliano?

**Comment by aborruso** [comment]
@marcoalfano non so se riesco per il 5, ma si può fare. Vediamo

**Comment by marcoalfano** [comment]
No problem se non riesci per il 5 ;) ma al limite non si può fare creare una pagina nonportale.opendatacampania.it con un redirect sull'indirizzo attuale?
