### ISSUE TITLE
Separatore formato dati

### ISSUE THREAD

**Issue by aborruso** [opendatacampania/nonportaleregionecampania#6]
@marcoalfano nel foglio elettonico i formati sono da separare con `;`, altrimenti vengono conteggiati male in home.

![2016-02-25_19h27_04](https://cloud.githubusercontent.com/assets/30607/13329749/f8e74fbc-dbf5-11e5-9787-59a3b0bd90e4.png)

**Comment by marcoalfano** [comment]
Okk...avevo dimenticato!
