### ISSUE TITLE
aggiungere colonne spreadsheet

### ISSUE THREAD

**Issue by marcoalfano** [opendatacampania/nonportaleregionecampania#8]
@aborruso devo aggiungere due colonne (all'ultimo) allo spreadsheet. Lo faccio io o tu?

1) Colonna che contiene i link a dati che vengono liberati.
A proposito, dove mettiamo eventuali file che creaiamo con i dati liberati? Direttamente nel git o meglio in una cartella apposita su drive?

2) Colonna che contiene link a elaborazioni/visualizzazioni dei dati pubblicati sul sistema regionale ITER

**Comment by aborruso** [comment]
@marcoalfano se le aggiungi in fondo, nello sheet "Censimento", nessun problema.
Fammi sapere se queste due colonne devono essere anche visualizzate sul web.

Per i dati che verranno liberati, se ti riferisci a dati che liberete il 5, direi nel posto più comodo a voi. Tenete presente che avete questa [organizzazione](https://github.com/opendatacampania) su github, su cui si possono aggiungere altri repo.

**Comment by marcoalfano** [comment]
@aborruso ho aggiunto le due colonne.
Si dovrebbero essere visualizzate (il 5 marzo faremo un esempio di creazione di file aperto e geolocalizzazione su mappa dei musei campani), ma se non ci arrivi li faccio vedere direttametne dallo spreadsheet.
